---
- name: Check SSH connection
  hosts: all
  gather_facts: false

  tasks:
    - name: Test SSH connection
      ansible.builtin.ping:
      run_once: true
      tags:
        - always

- name: Deploy monitoring stack
  hosts: monitoring
  become: true

  roles:
    - { role: monitoring, tags: prometheus }
    ### OR
    # - { role: prometheus, tags: prometheus }
    # - { role: grafana, tags: grafana }
